ws:
  router: "/onebot/v11/ws"
  allow-origins: "*"
  text-buffer-size: "819200"

bot:
  super-users: [1942422015] #超级用户

errie:
  client-id:
  client-secret:

api-space:
  token:

reecho:
  api-key:
  web-token: 

retrofit:
  global-timeout:
    connect-timeout-ms: 10000
    read-timeout-ms: 30000
    write-timeout-ms: 30000
  global-log:
    enable: true
    
logging:
  file:
    name: log/huhubot.log
  level:
    root: info 
  pattern:
    console: '%d{MM-dd HH:mm:ss} %clr([%level]){green} %clr(HuhuBot){cyan} | %clr(%thread){magenta} %msg%n'
