bot:
  super-users: [1942422015] #超级用户
  command-prefixes: []
  test_group:
  ali-refresh-token:

wx:
  client-id:
  client-secret:

reecho:
  api-key:
  web-token:

retrofit:
  global-timeout:
    connect-timeout-ms: 10000
    read-timeout-ms: 30000
    write-timeout-ms: 30000
  global-log:
    enable: true
